package com.crm.pvt.hapinicrm;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class privacy extends AppCompatActivity {
TextView text;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_privacy);
    text = (findViewById(R.id.privacypolicy));
    text.setText("PRIVACY POLICY\n"+"\nHapini Solutions Pvt. Ltd. understands the price of client' (s) privacy. Here, inside the privacy policy,\n"+"we tend to unit describing the privacy information that we tend together once you utilize the services via CRM (CUSTOMERS RELATION MANAGEMENT) and therefore the method we tend to disclose and use that information.\n\n\n" +

            "Any object of protestant or criticism as per these benchmarks, information|the info|the information} Technology (Reasonable Security Practices and Procedures and Sensitive Personal information or Information) Rules 2011 and data Technology (Intermediaries Guidelines) Rules, 2011 shall have alluded to L.I.G twenty 5 SF Barra 3, Kanpur, India. Hapini will direct all the complaints and criticisms within thirty days or one month of lodging an identical.\n" +
            "If anyone of the users set to use services provided by our application, it's a necessity that he/she trust our Privacy Policies and Terms & Conditions. Hapini resolution designed the hapini CRM app as a Free app. This SERVICE is provided by Hapini resolution at no worth and is meant to be used as is. If anyone decides to use our services, This page is employed to tell guests regarding our policies with the gathering, use, and revelation of non-public information.\n" +
            "If you choose on to use our Service, then you suit the gathering and use of information in respect to this policy. The private information collected by U.S.A. is used for providing and up the Service. We'll not use or share your information with anyone except as delineate throughout this Privacy Policy.\n" +
            "The terms utilized throughout this Privacy Policy have a daily meaning as in our Terms and Conditions, that's accessible at hapini CRM unless otherwise made public throughout this Privacy Policy. So our app take user permissions on these segments: \n\n"+"INTERNET\n\n"+"ACCESS_NETWORK_STATE\n\n"+"CALL_PHONE\n\n"+"MANAGE_CALLS\n\n"+"READ_EXTERNAL_STORAGE\n\n"+"WRITE_EXTERNAL_STORAGE\n\n"+"READ_PHONE_STATE\n\n"+"Information assortment and Use: For a much better experience, whereas using our Service, we tend to may wish you to provide U.S.A. with certain face to face placeable information, at the side of but not restricted to Network State, Internet, Phone Calls. The knowledge that we tend to request is popping into to be preserved by U.S.A. and used as delineate throughout this privacy policy. The app can use third party services which might collect information that may not verify you. Link to privacy policy of third party service suppliers used by the app Google Play Services Google Analytics for base\n" +
            "Firebase Crashlytics Log Data Some other dependencies. We want to tell you that whenever you utilize our Service, throughout a case of a mistake within the app we tend to gather information {and information|and information|and data} (through third party products) on your phone referred to as Log knowledge. This log information consists of your device information science (Internet protocol) address, name of your device, version of your computer code (OS) version, our app configuration at the time of service and variety of extra statistics.\n" +
            "Cookies: Cookies unit files with barely amount of information that unit usually used as anonymous distinctive identifiers. These unit sent to your browser from the websites merely|that you just} merely visit and unit hold on your device's internal memory. This Service doesn't use these “cookies” expressly. However, the app may use third party code and libraries that use “cookies” to assemble information and improve their services. You've the selection to either accept or refuse these cookies and acknowledge once a cookie is being sent to your device. If you choose to refuse our cookies, you'll not be able to use some elements of this Service.\n" +
            "Service Providers: We may use third-party companies and folks because of later reasons: To facilitate our Service; To provide the Service on our behalf; To perform Service-related services; or To assist U.S.A. in analyzing, but our Service is used. We want {to information rm|to tell} users of this Service that these third parties have access to your Personal info. These service suppliers will perform the tasks assigned on our behalf. However, they're indebted to not disclose or use the knowledge for the opposite purpose.\n" +
            "Security: We try our utmost to use personal information provided by you to verify your safety and security. But detain mind that no technique of transmission over the online, or technique of electronic storage is 100% secure and reliable, that we tend to cannot guarantee its absolute security.\n" +
            "Links to various Sites: This Service may contain links to various sites. If you click on a third-party link, you'll be directed to it computing machine. Note that these external sites aren't operated by U.S.A. So we tend to advise every user to review the privacy policy before using these websites. We've no management over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.\n" +
            "Children’s Privacy: These Services don't address anyone below the age of 13. We tend to don't knowingly collect face to face placeable information from youngsters below 13 years recent. Within the case we tend to get that a baby below 13 has provided U.S.A. with personal information, we tend to straightaway delete this from our servers. If you're a parent or guardian, and you're\n" +
            "aware that your child has provided U.S.A. with personal information, please contact U.S.A. so as that we'll be able to do necessary actions.\n" +
            "Privacy policy update: We may update our Privacy Policy from time to time. Changes to our privacy policy would be timely updated, so it's powerfully urged to travel to our page oft. {we will|we'll|we unit going to} apprize all our service users if any new changes square measure created in our privacy policy on this page. This policy is effective as of 2021-06-25 Contact Us If you have any queries or suggestions concerning our Privacy Policy, don't hesitate to contact Us at support@hapini.in");
    }
}